# filename: create_bookmarks.py

# -------------------------------------------------------------------------- #

# File Name:        create_bookmarks.py
# Version:          2.1.2
# Language:         python script
# Flame Version:    2025.x
# Author:           Phil MAN - phil_man@mac.com
# Toolset:          MAN_MADE_MATERIAL: LOGIK-PROJEKT
# Created:          2024-04-20
# Modified:         2024-05-15
# Modifier:         Phil MAN - phil_man@mac.com

# Description:      This program defines functions to create bookmarks for 
#                   different dcc applications.

# Installation:     Copy the 'LOGIK-PROJEKT' repo to your GitHub directory,
#                   e.g. '/home/$USER/workspace/GitHub'

# Changelist:       The full changelist is at the end of this document.

# -------------------------------------------------------------------------- #

# ========================================================================== #
# This section imports the necessary modules.
# ========================================================================== #

import bpy


'''functions to create file browser bookmakrs for various dcc applications

'''

'''def create_blender_bookmark(bookmark_name, directory):
    # Set the active directory for the file browser
    bpy.ops.wm.path_open(filepath=directory)
    
    # Add a bookmark for the current directory
    bpy.ops.file.bookmark_add(name=bookmark_name)

    blender -b -P /path/to/your/script.py

    print(f"Bookmark '{bookmark_name}' created successfully!")

# Example usage:
create_blender_bookmark("MyBookmark", "/path/to/directory")
'''

'''
/home/pman/.nuke/FileChooser_Favorites.pref

# Do not edit this file, it is automatically generated by Nuke.
add_favorite_dir Home Home home_dir ~/
add_favorite_dir Root Root root_dir /
add_favorite_dir Current Current "" [pwd]/
add_favorite_dir Nuke Nuke icon16 "[file dir $program_name]/"
add_favorite_dir -image -script -project -python -font -geo -misc -sequence JOBS JOBS "" /JOBS /JOBS/
add_favorite_dir -image -script -project -python -font -geo -misc -sequence dry_run_01 dry_run_01 "" dry_run_01_tooltip /JOBS/dry_run_01/

# End of generated file.'''