#!/bin/bash

# Define the base directory
base_dir="software"

# Create directories and touch files
mkdir -p "$base_dir/aftereffects/01_GFX_Stringouts/Adobe After Effects Auto-Save"
mkdir -p "$base_dir/aftereffects/01_GFX_Stringouts/_renders/YYYY-MM-DD"
mkdir -p "$base_dir/aftereffects/SH0010/Adobe After Effects Auto-Save"
mkdir -p "$base_dir/aftereffects/SH0010/_renders"
mkdir -p "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11"
mkdir -p "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/03_Ref"
mkdir -p "$base_dir/aftereffects/SLATE_TEMPLATE/0000_SLATE_TEMPLATE_YYYYMMDD_xx_AME"
mkdir -p "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save"
mkdir -p "$base_dir/c4d/SH0010/_renders"
mkdir -p "$base_dir/c4d/SH0010/tex"
mkdir -p "$base_dir/houdini"
mkdir -p "$base_dir/illustrator"
mkdir -p "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Document fonts"
mkdir -p "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Links"
mkdir -p "$base_dir/maya"
mkdir -p "$base_dir/photoshop"
mkdir -p "$base_dir/premiere/Adobe Premiere Pro Auto-Save"
mkdir -p "$base_dir/premiere/SRTs"
mkdir -p "$base_dir/resolve"
mkdir -p "$base_dir/unity"
mkdir -p "$base_dir/unreal_engine"

# Touch files
touch "$base_dir/aftereffects/01_GFX_Stringouts/0000_JOB_TEMPLATE_YYYYMMDD_xx.aep"
touch "$base_dir/aftereffects/01_GFX_Stringouts/Adobe After Effects Auto-Save/0000_JOB_TEMPLATE_YYYYMMDD_xx auto-save 1.aep"
touch "$base_dir/aftereffects/01_GFX_Stringouts/Adobe After Effects Auto-Save/0000_JOB_TEMPLATE_YYYYMMDD_xx auto-save 2.aep"
touch "$base_dir/aftereffects/01_GFX_Stringouts/Adobe After Effects Auto-Save/0000_JOB_TEMPLATE_YYYYMMDD_xx auto-save 3.aep"
touch "$base_dir/aftereffects/01_GFX_Stringouts/Adobe After Effects Auto-Save/0000_JOB_TEMPLATE_YYYYMMDD_xx auto-save 4.aep"
touch "$base_dir/aftereffects/AE_OUTPUT_MODULES_20240110.aom"
touch "$base_dir/aftereffects/SH0010/0000_JOB_TEMPLATE_YYYYMMDD_xx.aep"
touch "$base_dir/aftereffects/SH0010/Adobe After Effects Auto-Save/0000_JOB_TEMPLATE_YYYYMMDD_xx auto-save 1.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/00000_Slate_Template_16x9_MMDDYY.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/00000_Slate_Template_16x9_MMDDYYReport.txt"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO2_SLATE_kl_v001 - TEST_02.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO2_SLATE_kl_v001 - TEST_06_25_2024.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO2_SLATE_kl_v001 - TEST_09_29_2024.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO_SLATE_kl_v001 - Sheet1.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO_SLATE_kl_v002 - Sheet1.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/(Footage)/02_Assets/internal/2024-06-11/ASO_SLATE_kl_v003 - Sheet1.csv"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/00000_Slate_Template_16x9_MMDDYY folder/03_Ref/SO_Slate_2398-20160229-PRORES_HQ_REF_1920x1080.mov"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/0000_SLATE_TEMPLATE_YYYYMMDD_xx.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/0000_SLATE_TEMPLATE_YYYYMMDD_xx_AME/tmpAEtoAMEProject-ISCI_TITLE_RESOLUTION.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/00000_Slate_Template_16x9_MMDDYY auto-save 1.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/0000_SLATE_TEMPLATE_YYYYMMDD_xx auto-save 5.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/0000_SLATE_TEMPLATE_YYYYMMDD_xx auto-save 6.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/0000_SLATE_TEMPLATE_YYYYMMDD_xx auto-save 7.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/0000_SLATE_TEMPLATE_YYYYMMDD_xx auto-save 8.aep"
touch "$base_dir/aftereffects/SLATE_TEMPLATE/Adobe After Effects Auto-Save/0000_SLATE_TEMPLATE_YYYYMMDD_xx auto-save 9.aep"
touch "$base_dir/c4d/SH0010/0000_SH0010_xx_v001.c4d"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/00000_JOB_NAME_2024MMDD_xx.indd"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/00000_JOB_NAME_YYYYMMDD_xx.idml"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/00000_JOB_NAME_YYYYMMDD_xx.indd"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/00000_JOB_NAME_YYYYMMDD_xx.pdf"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Document fonts/AdobeFnt23.lst"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Document fonts/AdobeFnt24.lst"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Document fonts/Apercu-Bold.otf"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Document fonts/Apercu.otf"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Links/210406_SignificantOthers_LogoTypeHorizontal_white.ai"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Links/210406_SignificantOthers_LogoTypeIcon_White.ai"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Links/Significant_Ohers_LogoOnly_White.ai"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder/Links/Significant_Ohers_Logo_White.ai"
touch "$base_dir/Indesign/00000_JOB_NAME_YYYYMMDD_xx Folder.zip"
touch "$base_dir/premiere/SRTs/xxxxx_jobtitle_AudioQC_xx_v001 copy.prproj"
touch "$base_dir/premiere/SRTs/xxxxx_jobtitle_SRT_xx_v001.prproj"