#!/bin/bash
touch function_00-docstring.py
touch function_01-separators.py
touch function_02-date.py
touch function_03-banners.py
touch function_04-setup.py
touch function_05-environment.py
touch function_06-adsk_info.py
touch function_07-projekt_name.py
touch function_08-projekt_resolution.py
touch function_09-projekt_depth.py
touch function_10-projekt_framerate.py
touch function_11-projekt_color_science.py
touch function_12-projekt_start_frame.py
touch function_13-projekt_summary.py
touch function_14-rsync_options.py
touch function_15-projekt_flame.py
touch function_16-projekt_flame_dirs.py
touch function_17-job_dirs.py
touch function_18-sync_batch.py
touch function_19-sync_mediaimport.py
touch function_20-sync_bookmarks.py
touch function_21-sync_overlays.py
touch function_22-sync_python.py
touch function_23-sync_io.py
touch function_24-sync_col_policies.py
touch function_25-sync_col_transforms.py
touch function_26-add_color_policy.py
touch function_27-link_setup_dirs.py
touch function_28-backup_logs.py
touch function_29-create_archive_script.py
touch function_30-create_backup_script.py