# Function:         render_node_type_toggle

def render_node_type_toggle():

        if self.write_file_render_node_type_push_btn.text() == 'Render Node':
        self.write_file_setup_label.setDisabled(True)
        self.write_file_media_path_label.setDisabled(True)
        self.write_file_pattern_label.setDisabled(True)
        self.write_file_type_label.setDisabled(True)
        self.write_file_frame_index_label.setDisabled(True)
        self.write_file_padding_label.setDisabled(True)
        self.write_file_compression_label.setDisabled(True)
        self.write_file_settings_label.setDisabled(True)
        self.write_file_version_name_label.setDisabled(True)
        self.write_file_media_path_lineedit.setDisabled(True)
        self.write_file_pattern_lineedit.setDisabled(True)
        self.write_file_create_open_clip_lineedit.setDisabled(True)
        self.write_file_include_setup_lineedit.setDisabled(True)
        self.write_file_version_name_lineedit.setDisabled(True)
        self.write_file_padding_slider.setDisabled(True)
        self.write_file_image_format_push_btn.setDisabled(True)
        self.write_file_compression_push_btn.setDisabled(True)
        self.write_file_frame_index_push_btn.setDisabled(True)
        self.write_file_pattern_token_btn.setDisabled(True)
        self.write_file_browse_btn.setDisabled(True)
        self.write_file_include_setup_btn.setDisabled(True)
        self.write_file_create_open_clip_btn.setDisabled(True)
        self.write_file_open_clip_token_btn.setDisabled(True)
        self.write_file_include_setup_token_btn.setDisabled(True)
        else:
        self.write_file_setup_label.setDisabled(False)
        self.write_file_media_path_label.setDisabled(False)
        self.write_file_pattern_label.setDisabled(False)
        self.write_file_type_label.setDisabled(False)
        self.write_file_frame_index_label.setDisabled(False)
        self.write_file_padding_label.setDisabled(False)
        self.write_file_compression_label.setDisabled(False)
        self.write_file_settings_label.setDisabled(False)
        self.write_file_version_name_label.setDisabled(False)
        self.write_file_media_path_lineedit.setDisabled(False)
        self.write_file_pattern_lineedit.setDisabled(False)
        self.write_file_create_open_clip_lineedit.setDisabled(False)
        self.write_file_include_setup_lineedit.setDisabled(False)
        self.write_file_version_name_lineedit.setDisabled(False)
        self.write_file_padding_slider.setDisabled(False)
        self.write_file_image_format_push_btn.setDisabled(False)
        self.write_file_compression_push_btn.setDisabled(False)
        self.write_file_frame_index_push_btn.setDisabled(False)
        self.write_file_pattern_token_btn.setDisabled(False)
        self.write_file_browse_btn.setDisabled(False)
        self.write_file_include_setup_btn.setDisabled(False)
        self.write_file_create_open_clip_btn.setDisabled(False)
        self.write_file_open_clip_token_btn.setDisabled(False)
        self.write_file_include_setup_token_btn.setDisabled(False)

        write_file_create_open_clip_btn_check()

        write_file_include_setup_btn_check()
